{{- if gt (int (default 1 .Values.replicaCount)) 1 -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "actions-runner-controller-2.leaderElectionRoleBinding" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "actions-runner-controller-2.leaderElectionRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "actions-runner-controller-2.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}