{{- if and (eq .Values.containerMode.type "kubernetes") (not .Values.template.spec.serviceAccountName) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "auto-scaling-runner-set.kubeModeRoleName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "auto-scaling-runner-set.kubeModeRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "auto-scaling-runner-set.kubeModeServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}