{{- if and (eq .Values.containerMode.type "kubernetes") (not .Values.template.spec.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auto-scaling-runner-set.kubeModeServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto-scaling-runner-set.labels" . | nindent 4 }}
{{- end }}